# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2576eb90684277c297c8bbf1ebf58beefdb1f4ecc4c8aafc9820fb5b1199acab53e5b1627009df197f599a17668bcf2327fe464d7ae8f4b315c0a3a5cfcf06d0

test:
  secret_key_base: 091073aaa46783fb032ac8bb82ef1b45d8bf3e67b6d320266617bbadf93be3e8c2a1ca85efd6cf8a6d85194afacc605bd7b9f2b12fa6f37b560151ae22d30318

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
